version: "3"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URL=${MONGO_URL}
      - DB_MONGO=${DB_MONGO}
      - JWT_SECRET=${JWT_SECRET}
      - USERNAME_ADMIN=${USERNAME_ADMIN}
      - EMAIL_ADMIN=${EMAIL_ADMIN}
      - PASSWORD_ADMIN=${PASSWORD_ADMIN}
    depends_on:
      - mongo
    volumes:
      - .:/src
    container_name: feed-app

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    container_name: mongo-db
